/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#e3beb8",
        "surface-container-high": "#e7e8e9",
        "secondary-fixed": "#ffdad9",
        "on-primary-container": "#ff907f",
        "on-tertiary-fixed-variant": "#2c4c4c",
        primary: "#610000",
        "on-error-container": "#93000a",
        "inverse-surface": "#2e3132",
        "on-primary-fixed": "#410000",
        "surface-variant": "#e1e3e4",
        "on-secondary-container": "#fffbff",
        "on-secondary-fixed": "#40000a",
        "surface-dim": "#d9dadb",
        background: "#f8f9fa",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#ffb3b3",
        "on-secondary-fixed-variant": "#920022",
        "inverse-on-surface": "#f0f1f2",
        tertiary: "#103232",
        "surface-container": "#edeeef",
        "on-primary-fixed-variant": "#920703",
        secondary: "#ba002e",
        "on-tertiary-container": "#94b6b6",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#002020",
        "secondary-container": "#e31c40",
        "inverse-primary": "#ffb4a8",
        "on-surface": "#191c1d",
        "primary-fixed": "#ffdad4",
        "surface-container-low": "#f3f4f5",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#8b0000",
        "tertiary-fixed-dim": "#abcdcd",
        "on-background": "#191c1d",
        outline: "#8e706b",
        "on-surface-variant": "#5a403c",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#284848",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#c6e9e9",
        "primary-fixed-dim": "#ffb4a8",
        "surface-tint": "#b52619",
        surface: "#f8f9fa",
        error: "#ba1a1a",
        "surface-container-highest": "#e1e3e4",
        "surface-bright": "#f8f9fa",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        "container-max": "1280px",
        unit: "8px",
        "margin-desktop": "48px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "headline-md": ["Manrope"],
        "headline-lg": ["Manrope"],
        "body-lg": ["Inter"],
        "label-md": ["JetBrains Mono"],
        "body-md": ["Inter"],
        "headline-xl": ["Manrope"],
        "headline-lg-mobile": ["Manrope"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": ["40px", { lineHeight: "48px", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
